language: java
sudo: false
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - branch-9_0
env:
  global: 
  - secure: b92BffjiSOEUgWjdD7CWqCkS8kRZ0nW4kmxkapzsKlY3MgoSRs/ZT5UrtGxDilPq0Ja5k8Ht7Oqod3ugztppZXt0lrmy1fRVL2ivJu/WkgwJW0pLN7qElpHae3Nva0RKzJp7ZRUrjTE/+DU7hVwPd8bZxsFWxhRw08EKSReHPCY=
  - secure: AgvHJrr8GkYBeWT2CxUAcMHIm+JJU/Xxt3ymj+iJkOu/O1GzTKRanuglttdFjflqGARlBPfrbYi4X+NDaLGP8DcRUsBNS3ef+E3cW5nkdq5B/AtA/bWE+zSlDEaDG9O/lhVJIXi9gIxDorTMkWIo3WwjcJcJQSkF3v9ZGYiI7WY=
  - secure: S/etldnezDZmc6UDqKREy53uQGbHpb5vUx8mue/CQRs8pwJwJEzlR2v3pG+fRTudwTEw42mKV6hTc3yU+Nylo278B5zP1PlbrERS8vTynRjBHPDSf2sTI9qyz+s7q6JggvP4L3ZoDDuodxbFghxc6l+3VmvTT4CXJ04GaeJxe1w=
before_script:
- python add_server.py
install: true
script:
- mvn -P coveralls cobertura:cobertura coveralls:report install
after_script:
- python restore_backups.py
