language: java
sudo: false
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - branch-9_0
env:
  global:
  - secure: ZJtCYq2K54/EcxwAUawFN7Q4FHDIMhT294gu1DUT0b2fbWd4gkQGW7PHeFjixCn66YXIUwA+rEUnvgyqS63uMd2mYq90XriOJXWpsHgILNPY1CJbIOZaeJT+zktTIShXvHKfBfnDxAzhEdiYRFrZ+BXyMrztOsWSpxZ1vIwcjzE=
  - secure: VJ0Wgs91eueqPDnGyh9KZ2t8kEBSLergoatBZM+347pL/RFCDQ3COLzWyeIi6DIzfDZ/R8x/oFzOuS8NyQ7JRyid3LriUAu0pejADKE0aRbC4YBsCjCuYRB/yRTN3IMFvRE6Ql2+YdDD+llYTmrebiO4MJq7Uc4D4NfWFkfsoAw=
  - secure: StRXgi+6hg4P2MrkbzFsaHQ7cqkfx+UpzrJwAldV1Ohm7m4uaWyPI8Xfko63NNHa4UcpXOWb+b5KbYaKr8dfdAHAXkMhNSBiTcYlEaASZlA1VN3aqG3vqdCey94SWGptOHfhBDSzFdcNAwPagt2u/FAESu0veM70vms6C//rbCU=
before_script:
- python add_server.py
install: true
script:
- mvn -Pcoveralls cobertura:cobertura coveralls:report deploy
after_script:
- python restore_backups.py
